export default [
  {
    id: "1",
    image: "./assets/Women/air force 1 shadow.webp",
    title: "Air Force 1 Shadow",
    desc: "Classic and versatile, the Air Force 1 Shadow brings a bold twist to the iconic design.",
    price: "$299.99",
  },
  {
    id: "2",
    image: "./assets/Women/nike blazer low 77.webp",
    title: "Nike Blazer Low 77",
    desc: "With a sleek low-top profile, the Nike Blazer Low 77 offers a throwback style with modern comfort.",
    price: "$249.99",
  },
  {
    id: "3",
    image: "./assets/Women/nike cortez leather.webp",
    title: "Nike Cortez Leather",
    desc: "The Nike Cortez Leather delivers a timeless look with its clean, classic lines and premium leather.",
    price: "$199.99",
  },
  {
    id: "4",
    image: "./assets/Women/nike dunk low.webp",
    title: "Nike Dunk Low",
    desc: "Embrace heritage style with the Nike Dunk Low, a favorite for its vibrant colors and classic silhouette.",
    price: "$279.99",
  },
  {
    id: "5",
    image: "./assets/Women/nike free run.webp",
    title: "Nike Free Run",
    desc: "Designed for natural movement, the Nike Free Run offers lightweight flexibility and superior comfort.",
    price: "$159.99",
  },
  {
    id: "6",
    image: "./assets/Women/nike gamma force.webp",
    title: "Nike Gamma Force",
    desc: "Step into the future with the Nike Gamma Force, featuring advanced cushioning and futuristic design.",
    price: "$349.99",
  },
  {
    id: "7",
    image: "./assets/Women/nike invincible 3.webp",
    title: "Nike Invincible 3",
    desc: "Experience ultimate support and responsiveness with the Nike Invincible 3, perfect for long runs.",
    price: "$299.99",
  },
  {
    id: "8",
    image: "./assets/Women/nike phoenix waffle.webp",
    title: "Nike Phoenix Waffle",
    desc: "The Nike Phoenix Waffle blends retro style with modern comfort, inspired by the iconic waffle sole design.",
    price: "$189.99",
  },
];
