export default [
  {
    id: "1",
    image: "./assets/Men Shoes/dunklows.webp",
    title: "Dunk Lows",
    desc: "The Dunk Low delivers a timeless style with a street-ready look, featuring a comfortable fit and versatile design perfect for everyday wear.",
    price: "$120.00",
  },
  {
    id: "2",
    image: "./assets/Men Shoes/tatum 2 vortex.webp",
    title: "Tatum 2 Vortex",
    desc: "Designed in collaboration with Jayson Tatum, the Tatum 2 Vortex combines bold design with performance features, ideal for both on and off the court.",
    price: "$140.00",
  },
  {
    id: "3",
    image: "./assets/Men Shoes/jordan spizike low.webp",
    title: "Jordan Spizike Low",
    desc: "The Jordan Spizike Low fuses iconic eleMen Shoests from various Air Jordans into a unique and striking silhouette, offering both style and comfort.",
    price: "$175.00",
  },
  {
    id: "4",
    image: "./assets/Men Shoes/air jordan low 1.webp",
    title: "Air Jordan Low 1",
    desc: "The Air Jordan Low 1 is a low-top version of the classic Air Jordan 1, featuring premium materials and the iconic wings logo for a sleek, versatile look.",
    price: "$150.00",
  },
  {
    id: "5",
    image: "./assets/Men Shoes/air jordan 9g.webp",
    title: "Air Jordan 9G",
    desc: "The Air Jordan 9G combines basketball heritage with golf-ready performance, offering a blend of style and functionality on the course.",
    price: "$200.00",
  },
  {
    id: "6",
    image: "./assets/Men Shoes/nike invincible 3.webp",
    title: "Nike Invincible 3",
    desc: "Built for serious runners, the Nike Invincible 3 provides unparalleled cushioning and support with its ZoomX foam and breathable design.",
    price: "$180.00",
  },
  {
    id: "7",
    image: "./assets/Men Shoes/nike sb dunk low pro.webp",
    title: "Nike SB Dunk Low Pro",
    desc: "The Nike SB Dunk Low Pro is a skateboarding classic, known for its durable construction, responsive cushioning, and bold colorways.",
    price: "$110.00",
  },
  {
    id: "8",
    image: "./assets/Men Shoes/nike air max sc.webp",
    title: "Nike Air Max SC",
    desc: "The Nike Air Max SC delivers retro-inspired style with modern comfort, featuring visible Air cushioning and a clean, classic look.",
    price: "$130.00",
  },
];
